repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false
        args: ["--verbose"]

      - id: black
        name: black
        entry: black --config ./pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false
        args: ["--verbose"]

      - id: flake8
        name: flake8
        entry: flake8 --config ./setup.cfg .
        language: system
        types: [ python ]
        pass_filenames: false
        args: ["--verbose"]
